// <auto-generated />
namespace PracticalWerewolf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoutePlanning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoutePlanning));
        
        string IMigrationMetadata.Id
        {
            get { return "201704131724547_RoutePlanning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
